/*
 * OCM SMTP Service API
 *
 * Manages SMTP credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ClusterMeta struct for ClusterMeta
type ClusterMeta struct {
	Id        string `json:"id,omitempty"`
	Kind      string `json:"kind,omitempty"`
	Href      string `json:"href,omitempty"`
	ClusterID string `json:"clusterID,omitempty"`
}
