/*
 * OCM SMTP Service API
 *
 * Manages SMTP credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmtpDeleteRequest struct for SmtpDeleteRequest
type SmtpDeleteRequest struct {
	ClusterID string `json:"clusterID,omitempty"`
}
