/*
 * OCM SMTP Service API
 *
 * Manages SMTP credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Smtp struct for Smtp
type Smtp struct {
	Id         string    `json:"id,omitempty"`
	Kind       string    `json:"kind,omitempty"`
	Href       string    `json:"href,omitempty"`
	SendGridID string    `json:"sendGridID,omitempty"`
	Host       string    `json:"host,omitempty"`
	Port       string    `json:"port,omitempty"`
	Tls        string    `json:"tls,omitempty"`
	Username   string    `json:"username,omitempty"`
	Password   string    `json:"password,omitempty"`
	CreatedAt  time.Time `json:"created_at,omitempty"`
	UpdatedAt  time.Time `json:"updated_at,omitempty"`
}
