/*
 * OCM SMTP Service API
 *
 * Manages SMTP credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ErrorListAllOf struct for ErrorListAllOf
type ErrorListAllOf struct {
	Items []Error `json:"items,omitempty"`
}
