/*
 * OCM SMTP Service API
 *
 * Manages SMTP credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmtpListAllOf struct for SmtpListAllOf
type SmtpListAllOf struct {
	Items []Smtp `json:"items,omitempty"`
}
