/*
 * OCM SMTP Service API
 *
 * Manages SMTP credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmtpList struct for SmtpList
type SmtpList struct {
	Kind  string `json:"kind"`
	Page  int32  `json:"page"`
	Size  int32  `json:"size"`
	Total int32  `json:"total"`
	Items []Smtp `json:"items"`
}
